<?php

/**
 * @file
 * Primary module hooks for Localgov Gin Login module.
 */

/**
 * Implements hook_gin_login_route_definitions_alter().
 */
function localgov_gin_login_route_definitions_alter(&$route_definitions) {
  if (\Drupal::moduleHandler()->moduleExists('gin_login')) {
    foreach($route_definitions as &$route_definition) {
      if (in_array('gin_login_preprocess_ginlogin', $route_definition['preprocess functions'] ?? [], TRUE)) {
        $route_definition['preprocess functions'][] = 'localgov_gin_login_preprocess_ginlogin';
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_gin_login_preprocess_ginlogin(&$variables) {
  if (_gin_login__check_path()) {
    $config = \Drupal::config('gin_login.settings');
    $theme = \Drupal::theme()->getActiveTheme()->getName();
    $themeUseDefaultIcon = theme_get_setting('icon_default', $theme);
    $fileUrlGenerator = \Drupal::service('file_url_generator');
    // #3258015: Make sure we're compatible with the new variant.
    if ($themeUseDefaultIcon === NULL) {
      $themeIconPath = theme_get_setting('logo.path', $theme);
      $themeUseDefaultIcon = theme_get_setting('logo.use_default', $theme);
    }
    $module_path = \Drupal::service('extension.list.module')->getPath('localgov_gin_login');

    $configData = $config->get();
    if (empty($variables['icon_path'])) {
      $variables['icon_path'] = $fileUrlGenerator->generateAbsoluteString($module_path . '/images/logo.svg');
    }

    // Show the site name.
    $variables['page']['content']['_site'] = [
      '#type' => 'markup',
      '#markup' => '<h2>' . $variables['site_name'] . '</h2>',
      '#weight' => -99,
    ];
    unset($variables['page']['content']['#sorted']);
  }
}

/**
 * Page_attachments_alter()
 */
function localgov_gin_login_page_attachments_alter(&$page) {
  if (_gin_login__check_path()) {
    $config = \Drupal::config('gin_login.settings');
    $configData = $config->get();
    $fileUrlGenerator = \Drupal::service('file_url_generator');
    $module_path = \Drupal::service('extension.list.module')->getPath('localgov_gin_login');

    $page['#attached']['library'][] = 'localgov_gin_login/login';

    // Remove the existing gin_login wallpaper library.
    $page['#attached']['library'] = array_filter($page['#attached']['library'], function($item) {
      return $item != 'gin_login/wallpaper' ? TRUE : FALSE;
    });

    // Add wallpaper library if no custom wallpaper is set.
    if ($configData['brand_image']['use_default'] != "0") {
      $page['#attached']['library'][] = 'localgov_gin_login/wallpaper';
      $page['#attached']['drupalSettings']['localgov_gin_login']['path'] = $fileUrlGenerator->generateAbsoluteString($module_path . '/images/wallpapers');
      $town_halls_feed = $module_path . '/js/town-halls.json';
      $page['#attached']['drupalSettings']['localgov_gin_login']['town_halls'] = json_decode(file_get_contents($town_halls_feed));
    }
  }
}